### ISSUE TITLE
Can't connect to gateway

### ISSUE THREAD

**Issue by Edremon** [terminal-discord/weechat-discord#100]
I'm trying to use weechat-discord (mk3), but after entering my discord token and reloading plugin, I get: `discord: Gateway still not successfully connected...  there is likely an issue with Discord or weecord, see logs for more details`.

I tried so find logs in my `$WEECHAT_HOME/logs` but found nothings, also tried to change `log_directive` to `trace` but that did nothing.

I also tried to find why it wasn't working and found out that the shard was stuck in `Identifying` state. I found nothing about being blocked in state in twilight issues. The weird things is that I tried with another discord account and it worked.

With the main branch, `/discord login` output nothing and no buffer open.

**Comment by Noskcaj19** [comment]
Mmm, given that one account works and another doesn't, that sounds like some new feature or property is causing twilight to fail to deserialize Ready.  Things like this happen with some frequency due to Discord sending client only data that twilight (being officially bot only) doesn't expect.

mk3 is still very much a WIP, and I still haven't gotten logging to a file and buffer working yet, so currently it only logs to a buffer when `open_tracing_window` is set to true.  I suspect you will find twilight error messages there.

**Comment by Edremon** [comment]
Setting `weecord.look.open_tracing_window` to on, and `weecord.general.log_directive` to `trace`, I get:
```
WARN twilight_gateway::shard::processor::r#impl: processing incoming event failed: ProcessError { kind: ParsingPayload, source: Some(GatewayEventParsingError { source: Some(Error("data did not match any variant of untagged enum GuildStatus", line: 1, column: 1351147)), kind: Deserializing }) } shard_id=0 shard_total=1
WARN twilight_gateway::shard::processor::r#impl: processing incoming event failed: ProcessError { kind: EventTypeUnknown { event_type: Some("READY_SUPPLEMENTAL"), op: 0 }, source: None } shard_id=0 shard_total=1
WARN twilight_gateway::shard::processor::r#impl: processing incoming event failed: ProcessError { kind: EventTypeUnknown { event_type: Some("CHANNEL_UNREAD_UPDATE"), op: 0 }, source: None } shard_id=0 shard_total=1
```

**Comment by Edremon** [comment]
From what I understand, `GuildStatus` is only present in the fork of twilight used for this project.

This account is a lot older and in a lot of discord servers, the account that work probably doesn't have one that make twilight fail to parse.

**Comment by Noskcaj19** [comment]
I was able to replicate the issue with my testing account in 50+ guilds.

The `GuildStatus` bit was removed from twilight because a bot can never receive an `UnavailableGuild`, however I believe users still can (a lot was changed in gateway v9 and I'm not sure if I got everything right).  But in this case it's (probably) just a confusing error message due to it being an untagged serde item.  According to tracing twilight failed to deserialize a Guild: "unknown field `premium_progress_bar_enabled`".  So it's a new property that got added.

This field needs to get added in my fork of twilight and the problem should be fixed, the currently used version of twilight is just old.  It looks like this has already been in upstream twilight for a while, I just finished rebasing their changes so I can push an update later today.

Although the bigger issue is that this happens with some frequency, and I really just need to make unknown fields not a hard error.

Also while tracking this down I realized that the tracing level config option got broken recently and no longer lets you set tracing higher than warn (I set `WEECORD_LOG=twilight=trace` and ran weechat).

**Comment by Edremon** [comment]
Alright, thank you for the quick fix.

Relying on a library that doesn't want those patch upstream seem a bit annoying.

**Comment by Noskcaj19** [comment]
Twilight upstream has the new Guild fields (I just need to rebase my changes onto a new version),  unless you mean the client only features.  As far as I know no major libraries support those anymore since Discord looks dimly on anything that can support custom clients or self bots.

**Comment by Edremon** [comment]
Yes, I was talking about support for "self botting". I imagine if they did, they would get removed from all the places that share information about change in the api and that would make developing that kind of library way more annoying.

**Comment by Noskcaj19** [comment]
I have pushed the updated twilight, but it looks like it's going to be more work than I expected to update weecord to use the new version.
