### ISSUE TITLE
Can't use CLI with guilds w/spaces in names

### ISSUE THREAD

**Issue by mqp** [terminal-discord/weechat-discord#27]
Right now the `join`, `autojoin`, and `watch` commands split their input on spaces, so you're out of luck if you're trying to apply them to guild names that have spaces. (Discord guild names can have spaces!)

Guild names with spaces seem to work OK in other ways -- i.e. if I manually put their ID into the autojoin config, they load up just fine.

Incidentally, it's a little annoying to me to have to get the capitalization right on the names.

Possible remedies might include:

- Accept quoted strings in the CLI input.
- Accept guild IDs instead of names.
- Have some alternate way to specify the guild, like seeing a list of your guilds and specifying an index in the list.

**Comment by Noskcaj19** [comment]
This is an interesting problem because of how weechat (doesn't) parse commands.  As far as I can tell, most built in commands split on spaces or stop splitting after a certain point, and completion does not seem to have quoting or a way to escape spaces.

So right now the autocompletion for guilds and channels is case-insensitive and replaces spaces with underscores.  Capitalization was supposed to be ignored and that has been fixed in e558e41, which should make it easier to input names.

As for your points, I believe that it would be possible to implement quoting with some fairly invasive hooks (similar to what wee-slack does for nick completion) and that is something I want to look into (but is kinda blocked on the ffi changes).
Accepting ids as well as names is an interesting idea, and I my end goal is to have a ui buffer (like fset) or just list the guilds/channels with indices as an alternate method of selecting items would be more simple.

**Comment by Noskcaj19** [comment]
This should be pretty much solved and the alternative selection will be tracked in #30.
