### ISSUE TITLE
guild_name for status bar

### ISSUE THREAD

**Issue by Gagis** [terminal-discord/weechat-discord#34]
I'd like to edit my bar.status.items to display buffer_guild_name+:+buffer_short_name or something like that, but I don't know what variable I could pull to get the name of the discord server the channel belongs into. Does such a variable exist, and could it be added if not?

**Comment by Noskcaj19** [comment]
I don't believe such a variable exists yet, but sounds like it should be easy to add.

Since I'm not very familiar with weechat configuration, what would be the best way of providing that data?  It looks like string_eval_expression (which is what I'm assuming the bar uses) can access hdata. Would that give the bar access to the value? Or would it be able to access a buffer property?

**Comment by Gagis** [comment]
It is working beautifully. Thank you!
