### ISSUE TITLE
Contributing back to the rust-weechat bindings repo.

### ISSUE THREAD

**Issue by poljar** [terminal-discord/weechat-discord#35]
Hi there. 

I saw that you are using the rust-weechat bindings from my own fork of the original project and was wondering if you are planing on contributing the changes back or if you would like to setup a repo with shared ownership making it the new upstream.

I made recently a new weechat-macro crate that replaces the old macros in rust-weechat and I noticed that you improved the macros as well here https://github.com/terminal-discord/rust-weechat/commit/4ffce96bfac213374b5d16c04ff2d131cd46244b.

We are duplicating efforts by having this split up and it would be a shame if we end up with two slightly incompatible rust-weechat versions.

PS: My new macros are procedural macros and do not need byte strings to be passed to the [weechat_plugin!](https://github.com/poljar/rust-weechat/blob/master/sample/src/lib.rs#L138) macro, nor the length. While they are not completely done I think they are a nice improvement to how it used to be.

**Comment by Noskcaj19** [comment]
I would happy to open a PR to add most of the bindings I have added, but I am not very comfortable writing ffi code and I would like to look over some of the functions before I make a PR.

As for the macro, my recent changes were essentially an experiment to see if the macro could be implemented entirely with declarative macros and const-fn. And while it turns out everything but strings to byte arrays is possible with the current const features. I would rather not use proc macros but I think until the remaining features stabilize a proc macro is probably the best option.

As far as a shared repo, I don't have a ton of time for maintenance and my work on it would probably be entirely for support for weechat-discord, but I would be happy to help.
I've got a few ideas for changes I'll ask about on your repo.

**Comment by poljar** [comment]
> I would happy to open a PR to add most of the bindings I have added, but I am not very comfortable writing ffi code and I would like to look over some of the functions before I make a PR.

That's fine, there is no rush here, also the code doesn't need to be perfect to be merged. The lib is very much very early in the development phase.

> As for the macro, my recent changes were essentially an experiment to see if the macro could be implemented entirely with declarative macros and const-fn. And while it turns out everything but strings to byte arrays is possible with the current const features. I would rather not use proc macros but I think until the remaining features stabilize a proc macro is probably the best option.

I played around with the const features as well but decided against them since not everything was possible and they required rust nightly.

Is there a reason you want to avoid the proc macros? They seem to do everything we want, are far more readable if you ask me, and we can provide nice error messages.

> As far as a shared repo, I don't have a ton of time for maintenance and my work on it would probably be entirely for support for weechat-discord, but I would be happy to help.
> I've got a few ideas for changes I'll ask about on your repo.

That's fine, I can maintain the lib and be "upstream" if you're fine with it as well. Developing what you need for discord is also fine and even preferred. I work mostly on stuff I personally need as well.

Anyways, since you opened some pull request to my repo this question is answered. Closing this now. Thanks.

**Comment by Noskcaj19** [comment]
My aversion to proc macros is probably mostly because I've never really used them.  Although from what I have tested there isn't a way to replicate `$crate` from macro_rules! which requires dependent crates to pull libc and weechat_sys because a proc-macro crate can't `pub use` them.

I'll be looking into fixes for that though because at this time stable CTFE doesn't cut it.
