### ISSUE TITLE
Multiline messages

### ISSUE THREAD

**Issue by zeddidragon** [terminal-discord/weechat-discord#74]
I've tried with `multiline.pl` and `vimode.py`, but the message break up into seperate lines. This makes it impossible to share highlighted code blocks.

Is there some kind of restriction in weechat that makes multiline messages such a problem?

**Comment by Noskcaj19** [comment]
I would expect that those scripts should work, as far as I know weechat discord doesn't do anything "strange" with text input. I don't know enough of the weechat and multiline.pl internals to know how that works.  Although, I think `multiline.pl` may just send each line in the editor separately because of how irc works.

**Comment by Noskcaj19** [comment]
I looked around, turns out `multiline.pl` just sends each line as a separate message, that's just a limitation of weechat.  Although it looks like weeslack has a hack to detect multiple lines and send them as one message.  Some other scripts detect rapid messages and combine them into one.

**Comment by Noskcaj19** [comment]
Looks like support for this is coming in Weechat 2.9 weechat/weechat/pull/1063

**Comment by Noskcaj19** [comment]
Setting `/buffer set input_multiline 1` has been tested to work on the mk3 branch, and likely works on master as well
