### ISSUE TITLE
make install fails: "failed to run custom build command for 'weechat-sys v0.1.0'"

### ISSUE THREAD

**Issue by apisashla** [terminal-discord/weechat-discord#86]
I am running Rust 1.48.0 on Mac OS X Catalina 10.15.7. Full error message is as follows:

```
error: failed to run custom build command for `weechat-sys v0.1.0 (https://github.com/terminal-discord/rust-weechat?rev=d972dd9#d972dd9a)`

Caused by:
  process didn't exit successfully: `/Users/[USERNAME]/Code/terminal-discord/weechat-discord/target/release/build/weechat-sys-99a5b2c2d1cd31c8/build-script-build` (signal: 6, SIGABRT: process abort signal)
  --- stderr
  dyld: Library not loaded: @rpath/libclang.dylib
    Referenced from: /Users/[USERNAME]/Code/terminal-discord/weechat-discord/target/release/build/weechat-sys-99a5b2c2d1cd31c8/build-script-build
    Reason: image not found
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Apologies if this is simply a config error on my part, but I've been looking for alternate explanations without success. Thank you.

**Comment by Noskcaj19** [comment]
It would appear as though libclang is not installed.

**Comment by apisashla** [comment]
I thought so too at first, but it does appear to be installed normally under Xcode, which in turn seems to be installed at the appropriate location (I did reinstall the entire program recently, for better or worse.)

```
➜  ~ find /Applications/Xcode.app -name libclang.dylib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib
/Applications/Xcode.app/Contents/Frameworks/libclang.dylib
```

@rpath doesn't seem to be finding it during the build process for whatever reason. Again if something's off about this on my part, I'll close the issue of course, but it does seem to stand to reason that this should work.

**Comment by apisashla** [comment]
Per kencu's comment on [this page](https://trac.macports.org/ticket/54939) describing a similar issue with a different program, I found a workaround by symlinking the dylib directly into `@rpath`'s search path, like so:
```
sudo ln -s /Applications/Xcode.app/Contents/Frameworks/libclang.dylib /usr/local/lib/libclang.dylib
```
Rust now builds the program and it works fine, so if anyone else is experiencing this issue, I'd try the above. I don't think this is intended behavior, though - in theory, the previous libclang.dylib location should have worked, and has worked on previous installs.

**Comment by Noskcaj19** [comment]
Ok, I got some time to dig into this.  First off, sorry, libclang is supposed to be listed as a required dependency, and it isn't on the master branch (this has been fixed).  I have personally always had homebrew llvm installed.

Secondly, your workaround is interesting, because it means clang-sys is apparently bugged, because it is supposed to be able to find libclang from xcode installed in both the default location and from `xcode-select -p`, however I cannot seem to get it to work.
However, I was able to get compilation to work using xcode's libclang by setting `LD_LIBRARY_PATH`.  Setting `LIBCLANG_PATH` is also supposed to work, but didn't.  I upgraded bindgen and clang-sys in 5885127, which seems to have fixed that issue.
